In [57]:
import pandas as pd

In [58]:
df = pd.read_csv('financials.csv')
df

,Segment,Country,Product,Discount Band,Units Sold,Manufacturing Price,Sale Price,Gross Sales,Discounts,Sales,COGS,Profit,Date,Month Number,Month Name,Year
0,Government,Canada,Carretera,None,"$1,618.50",$3.00,$20.00,"$32,370.00",$-,"$32,370.00","$16,185.00","$16,185.00",01/01/2014,1,January,2014
1,Government,Germany,Carretera,None,"$1,321.00",$3.00,$20.00,"$26,420.00",$-,"$26,420.00","$13,210.00","$13,210.00",01/01/2014,1,January,2014
2,Midmarket,France,Carretera,None,"$2,178.00",$3.00,$15.00,"$32,670.00",$-,"$32,670.00","$21,780.00","$10,890.00",01/06/2014,6,June,2014
3,Midmarket,Germany,Carretera,None,$888.00,$3.00,$15.00,"$13,320.00",$-,"$13,320.00","$8,880.00","$4,440.00",01/06/2014,6,June,2014
4,Midmarket,Mexico,Carretera,None,"$2,470.00",$3.00,$15.00,"$37,050.00",$-,"$37,050.00","$24,700.00","$12,350.00",01/06/2014,6,June,2014
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
695,Small Business,France,Amarilla,High,"$2,475.00",$260.00,$300.00,"$7,42,500.00","$1,11,375.00","$6,31,125.00","$6,18,750.00","$12,375.00",01/03/2014,3,March,2014
696,Small Business,Mexico,Amarilla,High,$546.00,$260.00,$300.00,"$1,63,800.00","$24,570.00","$1,39,230.00","$1,36,500.00","$2,730.00",01/10/2014,10,October,2014
697,Government,Mexico,Montana,High,"$1,368.00",$5.00,$7.00,"$9,576.00","$1,436.40","$8,139.60","$6,840.00","$1,299.60",01/02/2014,2,February,2014
698,Government,Canada,Paseo,High,$723.00,$10.00,$7.00,"$5,061.00",$759.15,"$4,301.85","$3,615.00",$686.85,01/04/2014,4,April,2014
699,Channel Partners,United States of America,VTT,High,"$1,806.00",$250.00,$12.00,"$21,672.00","$3,250.80","$18,421.20","$5,418.00","$13,003.20",01/05/2014,5,May,2014

In [59]:
df.columns = df.columns.str.strip()

In [60]:
df.columns

Index(['Segment', 'Country', 'Product', 'Discount Band', 'Units Sold',
       'Manufacturing Price', 'Sale Price', 'Gross Sales', 'Discounts',
       'Sales', 'COGS', 'Profit', 'Date', 'Month Number', 'Month Name',
       'Year'],
      dtype='object')

In [61]:
df["id"] = df[['Segment', 'Country', 'Product', 'Date', 'Discount Band']].apply(lambda x:"-".join(x.astype(str).str.strip()).lower(), axis=1)
df["id"] = df['id'].str.replace('/','', regex=True)
df.insert(0, 'id', df.pop('id'))
df

,id,Segment,Country,Product,Discount Band,Units Sold,Manufacturing Price,Sale Price,Gross Sales,Discounts,Sales,COGS,Profit,Date,Month Number,Month Name,Year
0,government-canada-carretera-01012014-none,Government,Canada,Carretera,None,"$1,618.50",$3.00,$20.00,"$32,370.00",$-,"$32,370.00","$16,185.00","$16,185.00",01/01/2014,1,January,2014
1,government-germany-carretera-01012014-none,Government,Germany,Carretera,None,"$1,321.00",$3.00,$20.00,"$26,420.00",$-,"$26,420.00","$13,210.00","$13,210.00",01/01/2014,1,January,2014
2,midmarket-france-carretera-01062014-none,Midmarket,France,Carretera,None,"$2,178.00",$3.00,$15.00,"$32,670.00",$-,"$32,670.00","$21,780.00","$10,890.00",01/06/2014,6,June,2014
3,midmarket-germany-carretera-01062014-none,Midmarket,Germany,Carretera,None,$888.00,$3.00,$15.00,"$13,320.00",$-,"$13,320.00","$8,880.00","$4,440.00",01/06/2014,6,June,2014
4,midmarket-mexico-carretera-01062014-none,Midmarket,Mexico,Carretera,None,"$2,470.00",$3.00,$15.00,"$37,050.00",$-,"$37,050.00","$24,700.00","$12,350.00",01/06/2014,6,June,2014
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
695,small business-france-amarilla-01032014-high,Small Business,France,Amarilla,High,"$2,475.00",$260.00,$300.00,"$7,42,500.00","$1,11,375.00","$6,31,125.00","$6,18,750.00","$12,375.00",01/03/2014,3,March,2014
696,small business-mexico-amarilla-01102014-high,Small Business,Mexico,Amarilla,High,$546.00,$260.00,$300.00,"$1,63,800.00","$24,570.00","$1,39,230.00","$1,36,500.00","$2,730.00",01/10/2014,10,October,2014
697,government-mexico-montana-01022014-high,Government,Mexico,Montana,High,"$1,368.00",$5.00,$7.00,"$9,576.00","$1,436.40","$8,139.60","$6,840.00","$1,299.60",01/02/2014,2,February,2014
698,government-canada-paseo-01042014-high,Government,Canada,Paseo,High,$723.00,$10.00,$7.00,"$5,061.00",$759.15,"$4,301.85","$3,615.00",$686.85,01/04/2014,4,April,2014
699,channel partners-united states of america-vtt-...,Channel Partners,United States of America,VTT,High,"$1,806.00",$250.00,$12.00,"$21,672.00","$3,250.80","$18,421.20","$5,418.00","$13,003.20",01/05/2014,5,May,2014

In [62]:
numerik_df = df[['Units Sold', 'Manufacturing Price', 'Sale Price', 'Gross Sales', 'Discounts','Sales', 'COGS', 'Profit']]
for x in numerik_df:
    if df[x].dtype == 'object':
        df[x] = df[x].str.replace('$', '').str.replace('-', '0').str.replace(',','').str.strip().str.strip('()')

df

,id,Segment,Country,Product,Discount Band,Units Sold,Manufacturing Price,Sale Price,Gross Sales,Discounts,Sales,COGS,Profit,Date,Month Number,Month Name,Year
0,government-canada-carretera-01012014-none,Government,Canada,Carretera,None,1618.50,3.00,20.00,32370.00,0,32370.00,16185.00,16185.00,01/01/2014,1,January,2014
1,government-germany-carretera-01012014-none,Government,Germany,Carretera,None,1321.00,3.00,20.00,26420.00,0,26420.00,13210.00,13210.00,01/01/2014,1,January,2014
2,midmarket-france-carretera-01062014-none,Midmarket,France,Carretera,None,2178.00,3.00,15.00,32670.00,0,32670.00,21780.00,10890.00,01/06/2014,6,June,2014
3,midmarket-germany-carretera-01062014-none,Midmarket,Germany,Carretera,None,888.00,3.00,15.00,13320.00,0,13320.00,8880.00,4440.00,01/06/2014,6,June,2014
4,midmarket-mexico-carretera-01062014-none,Midmarket,Mexico,Carretera,None,2470.00,3.00,15.00,37050.00,0,37050.00,24700.00,12350.00,01/06/2014,6,June,2014
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
695,small business-france-amarilla-01032014-high,Small Business,France,Amarilla,High,2475.00,260.00,300.00,742500.00,111375.00,631125.00,618750.00,12375.00,01/03/2014,3,March,2014
696,small business-mexico-amarilla-01102014-high,Small Business,Mexico,Amarilla,High,546.00,260.00,300.00,163800.00,24570.00,139230.00,136500.00,2730.00,01/10/2014,10,October,2014
697,government-mexico-montana-01022014-high,Government,Mexico,Montana,High,1368.00,5.00,7.00,9576.00,1436.40,8139.60,6840.00,1299.60,01/02/2014,2,February,2014
698,government-canada-paseo-01042014-high,Government,Canada,Paseo,High,723.00,10.00,7.00,5061.00,759.15,4301.85,3615.00,686.85,01/04/2014,4,April,2014
699,channel partners-united states of america-vtt-...,Channel Partners,United States of America,VTT,High,1806.00,250.00,12.00,21672.00,3250.80,18421.20,5418.00,13003.20,01/05/2014,5,May,2014

In [63]:
df[['Units Sold', 'Manufacturing Price', 'Sale Price', 'Gross Sales', 'Discounts','Sales', 'COGS', 'Profit']] = df[['Units Sold', 'Manufacturing Price', 'Sale Price', 'Gross Sales', 'Discounts','Sales', 'COGS', 'Profit']].astype(float)
df

,id,Segment,Country,Product,Discount Band,Units Sold,Manufacturing Price,Sale Price,Gross Sales,Discounts,Sales,COGS,Profit,Date,Month Number,Month Name,Year
0,government-canada-carretera-01012014-none,Government,Canada,Carretera,None,1618.5,3.0,20.0,32370.0,0.00,32370.00,16185.0,16185.00,01/01/2014,1,January,2014
1,government-germany-carretera-01012014-none,Government,Germany,Carretera,None,1321.0,3.0,20.0,26420.0,0.00,26420.00,13210.0,13210.00,01/01/2014,1,January,2014
2,midmarket-france-carretera-01062014-none,Midmarket,France,Carretera,None,2178.0,3.0,15.0,32670.0,0.00,32670.00,21780.0,10890.00,01/06/2014,6,June,2014
3,midmarket-germany-carretera-01062014-none,Midmarket,Germany,Carretera,None,888.0,3.0,15.0,13320.0,0.00,13320.00,8880.0,4440.00,01/06/2014,6,June,2014
4,midmarket-mexico-carretera-01062014-none,Midmarket,Mexico,Carretera,None,2470.0,3.0,15.0,37050.0,0.00,37050.00,24700.0,12350.00,01/06/2014,6,June,2014
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
695,small business-france-amarilla-01032014-high,Small Business,France,Amarilla,High,2475.0,260.0,300.0,742500.0,111375.00,631125.00,618750.0,12375.00,01/03/2014,3,March,2014
696,small business-mexico-amarilla-01102014-high,Small Business,Mexico,Amarilla,High,546.0,260.0,300.0,163800.0,24570.00,139230.00,136500.0,2730.00,01/10/2014,10,October,2014
697,government-mexico-montana-01022014-high,Government,Mexico,Montana,High,1368.0,5.0,7.0,9576.0,1436.40,8139.60,6840.0,1299.60,01/02/2014,2,February,2014
698,government-canada-paseo-01042014-high,Government,Canada,Paseo,High,723.0,10.0,7.0,5061.0,759.15,4301.85,3615.0,686.85,01/04/2014,4,April,2014
699,channel partners-united states of america-vtt-...,Channel Partners,United States of America,VTT,High,1806.0,250.0,12.0,21672.0,3250.80,18421.20,5418.0,13003.20,01/05/2014,5,May,2014

In [64]:
df['Date'] = pd.to_datetime(df['Date'], format='mixed')
df

,id,Segment,Country,Product,Discount Band,Units Sold,Manufacturing Price,Sale Price,Gross Sales,Discounts,Sales,COGS,Profit,Date,Month Number,Month Name,Year
0,government-canada-carretera-01012014-none,Government,Canada,Carretera,None,1618.5,3.0,20.0,32370.0,0.00,32370.00,16185.0,16185.00,2014-01-01,1,January,2014
1,government-germany-carretera-01012014-none,Government,Germany,Carretera,None,1321.0,3.0,20.0,26420.0,0.00,26420.00,13210.0,13210.00,2014-01-01,1,January,2014
2,midmarket-france-carretera-01062014-none,Midmarket,France,Carretera,None,2178.0,3.0,15.0,32670.0,0.00,32670.00,21780.0,10890.00,2014-01-06,6,June,2014
3,midmarket-germany-carretera-01062014-none,Midmarket,Germany,Carretera,None,888.0,3.0,15.0,13320.0,0.00,13320.00,8880.0,4440.00,2014-01-06,6,June,2014
4,midmarket-mexico-carretera-01062014-none,Midmarket,Mexico,Carretera,None,2470.0,3.0,15.0,37050.0,0.00,37050.00,24700.0,12350.00,2014-01-06,6,June,2014
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
695,small business-france-amarilla-01032014-high,Small Business,France,Amarilla,High,2475.0,260.0,300.0,742500.0,111375.00,631125.00,618750.0,12375.00,2014-01-03,3,March,2014
696,small business-mexico-amarilla-01102014-high,Small Business,Mexico,Amarilla,High,546.0,260.0,300.0,163800.0,24570.00,139230.00,136500.0,2730.00,2014-01-10,10,October,2014
697,government-mexico-montana-01022014-high,Government,Mexico,Montana,High,1368.0,5.0,7.0,9576.0,1436.40,8139.60,6840.0,1299.60,2014-01-02,2,February,2014
698,government-canada-paseo-01042014-high,Government,Canada,Paseo,High,723.0,10.0,7.0,5061.0,759.15,4301.85,3615.0,686.85,2014-01-04,4,April,2014
699,channel partners-united states of america-vtt-...,Channel Partners,United States of America,VTT,High,1806.0,250.0,12.0,21672.0,3250.80,18421.20,5418.0,13003.20,2014-01-05,5,May,2014

In [65]:
df.duplicated().sum()

0

In [66]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 700 entries, 0 to 699
Data columns (total 17 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   id                   700 non-null    object
 1   Segment              700 non-null    object
 2   Country              700 non-null    object
 3   Product              700 non-null    object
 4   Discount Band        700 non-null    object
 5   Units Sold           700 non-null    float64
 6   Manufacturing Price  700 non-null    float64
 7   Sale Price           700 non-null    float64
 8   Gross Sales          700 non-null    float64
 9   Discounts            700 non-null    float64
 10  Sales                700 non-null    float64
 11  COGS                 700 non-null    float64
 12  Profit               700 non-null    float64
 13  Date                 700 non-null    datetime64[ns]
 14  Month Number         700 non-null    int64
 15  Month Name           700 non-null    object
 16  Year                 700 non-null    int64
dtypes: datetime64[ns](1), float64(8), int64(2), object(6)
memory usage: 93.1+ KB

mengubah dtype Units Sold, Manufacturing Price, Sale Price, Gross Sales, Discounts, Sales, COGS, Profit jadi integer
mengubah dtype Date
menghapus strip di setiap nama kolom
mengdrop Month Number, Month Name, Year
menghapus $ dan mengubah '-' di column discount jadi 0

surrogate key = segment - country - product - date

In [67]:
df

,id,Segment,Country,Product,Discount Band,Units Sold,Manufacturing Price,Sale Price,Gross Sales,Discounts,Sales,COGS,Profit,Date,Month Number,Month Name,Year
0,government-canada-carretera-01012014-none,Government,Canada,Carretera,None,1618.5,3.0,20.0,32370.0,0.00,32370.00,16185.0,16185.00,2014-01-01,1,January,2014
1,government-germany-carretera-01012014-none,Government,Germany,Carretera,None,1321.0,3.0,20.0,26420.0,0.00,26420.00,13210.0,13210.00,2014-01-01,1,January,2014
2,midmarket-france-carretera-01062014-none,Midmarket,France,Carretera,None,2178.0,3.0,15.0,32670.0,0.00,32670.00,21780.0,10890.00,2014-01-06,6,June,2014
3,midmarket-germany-carretera-01062014-none,Midmarket,Germany,Carretera,None,888.0,3.0,15.0,13320.0,0.00,13320.00,8880.0,4440.00,2014-01-06,6,June,2014
4,midmarket-mexico-carretera-01062014-none,Midmarket,Mexico,Carretera,None,2470.0,3.0,15.0,37050.0,0.00,37050.00,24700.0,12350.00,2014-01-06,6,June,2014
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
695,small business-france-amarilla-01032014-high,Small Business,France,Amarilla,High,2475.0,260.0,300.0,742500.0,111375.00,631125.00,618750.0,12375.00,2014-01-03,3,March,2014
696,small business-mexico-amarilla-01102014-high,Small Business,Mexico,Amarilla,High,546.0,260.0,300.0,163800.0,24570.00,139230.00,136500.0,2730.00,2014-01-10,10,October,2014
697,government-mexico-montana-01022014-high,Government,Mexico,Montana,High,1368.0,5.0,7.0,9576.0,1436.40,8139.60,6840.0,1299.60,2014-01-02,2,February,2014
698,government-canada-paseo-01042014-high,Government,Canada,Paseo,High,723.0,10.0,7.0,5061.0,759.15,4301.85,3615.0,686.85,2014-01-04,4,April,2014
699,channel partners-united states of america-vtt-...,Channel Partners,United States of America,VTT,High,1806.0,250.0,12.0,21672.0,3250.80,18421.20,5418.0,13003.20,2014-01-05,5,May,2014

In [68]:
df.columns = df.columns.str.replace(' ', '_', regex=True).str.lower()
df

,id,segment,country,product,discount_band,units_sold,manufacturing_price,sale_price,gross_sales,discounts,sales,cogs,profit,date,month_number,month_name,year
0,government-canada-carretera-01012014-none,Government,Canada,Carretera,None,1618.5,3.0,20.0,32370.0,0.00,32370.00,16185.0,16185.00,2014-01-01,1,January,2014
1,government-germany-carretera-01012014-none,Government,Germany,Carretera,None,1321.0,3.0,20.0,26420.0,0.00,26420.00,13210.0,13210.00,2014-01-01,1,January,2014
2,midmarket-france-carretera-01062014-none,Midmarket,France,Carretera,None,2178.0,3.0,15.0,32670.0,0.00,32670.00,21780.0,10890.00,2014-01-06,6,June,2014
3,midmarket-germany-carretera-01062014-none,Midmarket,Germany,Carretera,None,888.0,3.0,15.0,13320.0,0.00,13320.00,8880.0,4440.00,2014-01-06,6,June,2014
4,midmarket-mexico-carretera-01062014-none,Midmarket,Mexico,Carretera,None,2470.0,3.0,15.0,37050.0,0.00,37050.00,24700.0,12350.00,2014-01-06,6,June,2014
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
695,small business-france-amarilla-01032014-high,Small Business,France,Amarilla,High,2475.0,260.0,300.0,742500.0,111375.00,631125.00,618750.0,12375.00,2014-01-03,3,March,2014
696,small business-mexico-amarilla-01102014-high,Small Business,Mexico,Amarilla,High,546.0,260.0,300.0,163800.0,24570.00,139230.00,136500.0,2730.00,2014-01-10,10,October,2014
697,government-mexico-montana-01022014-high,Government,Mexico,Montana,High,1368.0,5.0,7.0,9576.0,1436.40,8139.60,6840.0,1299.60,2014-01-02,2,February,2014
698,government-canada-paseo-01042014-high,Government,Canada,Paseo,High,723.0,10.0,7.0,5061.0,759.15,4301.85,3615.0,686.85,2014-01-04,4,April,2014
699,channel partners-united states of america-vtt-...,Channel Partners,United States of America,VTT,High,1806.0,250.0,12.0,21672.0,3250.80,18421.20,5418.0,13003.20,2014-01-05,5,May,2014

In [69]:
dup_df = df.groupby('id').agg({'gross_sales':'max'})
dup_df

                                                    gross_sales
id
channel partners-canada-amarilla-01042014-high          42246.0
channel partners-canada-amarilla-01092013-high          33132.0
channel partners-canada-carretera-01022014-high         23244.0
channel partners-canada-carretera-01082014-medium       22608.0
channel partners-canada-carretera-01092014-low          17340.0
...                                                         ...
small business-united states of america-vtt-010...     762300.0
small business-united states of america-vtt-010...     560100.0
small business-united states of america-vtt-011...     688200.0
small business-united states of america-vtt-011...     303000.0
small business-united states of america-vtt-011...     242400.0

[688 rows x 1 columns]

In [70]:
dupdup_df = dup_df.reset_index().set_index(['id', 'gross_sales'])
dupdup_df

Empty DataFrame
Columns: []
Index: [(channel partners-canada-amarilla-01042014-high, 42246.0), (channel partners-canada-amarilla-01092013-high, 33132.0), (channel partners-canada-carretera-01022014-high, 23244.0), (channel partners-canada-carretera-01082014-medium, 22608.0), (channel partners-canada-carretera-01092014-low, 17340.0), (channel partners-canada-carretera-01102013-medium, 27588.0), (channel partners-canada-carretera-01102014-low, 15540.0), (channel partners-canada-carretera-01122013-low, 10896.0), (channel partners-canada-montana-01062014-none, 30216.0), (channel partners-canada-montana-01112014-medium, 27852.0), (channel partners-canada-paseo-01062014-none, 30216.0), (channel partners-canada-paseo-01072014-high, 48312.0), (channel partners-canada-paseo-01102013-medium, 27588.0), (channel partners-canada-paseo-01102014-low, 15540.0), (channel partners-canada-paseo-01112013-high, 26664.0), (channel partners-canada-paseo-01122014-medium, 29172.0), (channel partners-canada-velo-01032014-medium, 7176.0), (channel partners-canada-velo-01122014-medium, 29172.0), (channel partners-canada-vtt-01012014-medium, 38934.0), (channel partners-canada-vtt-01052014-high, 25308.0), (channel partners-france-amarilla-01082014-high, 29700.0), (channel partners-france-amarilla-01102014-high, 16716.0), (channel partners-france-amarilla-01122013-medium, 3672.0), (channel partners-france-carretera-01022014-medium, 22380.0), (channel partners-france-carretera-01092014-low, 32052.0), (channel partners-france-carretera-01102013-high, 14376.0), (channel partners-france-montana-01062014-low, 22812.0), (channel partners-france-montana-01112014-medium, 28104.0), (channel partners-france-paseo-01062014-low, 22812.0), (channel partners-france-paseo-01072014-high, 29106.0), (channel partners-france-paseo-01102013-high, 14376.0), (channel partners-france-paseo-01102014-high, 16716.0), (channel partners-france-paseo-01112013-low, 21420.0), (channel partners-france-paseo-01122014-low, 12660.0), (channel partners-france-velo-01032014-medium, 23604.0), (channel partners-france-velo-01122014-low, 12660.0), (channel partners-france-vtt-01012014-high, 20808.0), (channel partners-france-vtt-01042014-medium, 20862.0), (channel partners-france-vtt-01052014-low, 10392.0), (channel partners-france-vtt-01092013-medium, 26808.0), (channel partners-germany-amarilla-01082014-high, 30888.0), (channel partners-germany-amarilla-01102014-high, 5664.0), (channel partners-germany-amarilla-01122013-high, 21240.0), (channel partners-germany-carretera-01022014-medium, 13392.0), (channel partners-germany-carretera-01092014-medium, 18960.0), (channel partners-germany-carretera-01102013-low, 9192.0), (channel partners-germany-montana-01062014-none, 18540.0), (channel partners-germany-montana-01112014-medium, 28104.0), (channel partners-germany-paseo-01072014-none, 4404.0), (channel partners-germany-paseo-01102013-low, 9192.0), (channel partners-germany-paseo-01112013-medium, 21300.0), (channel partners-germany-paseo-01122014-high, 12156.0), (channel partners-germany-velo-01032014-none, 25932.0), (channel partners-germany-velo-01062014-none, 18540.0), (channel partners-germany-velo-01102014-high, 5664.0), (channel partners-germany-velo-01122014-high, 12156.0), (channel partners-germany-vtt-01012014-low, 29748.0), (channel partners-germany-vtt-01042014-none, 34056.0), (channel partners-germany-vtt-01052014-medium, 10560.0), (channel partners-germany-vtt-01092013-medium, 26580.0), (channel partners-mexico-amarilla-01082014-medium, 13476.0), (channel partners-mexico-amarilla-01102014-high, 4920.0), (channel partners-mexico-amarilla-01122013-medium, 16500.0), (channel partners-mexico-carretera-01022014-medium, 8724.0), (channel partners-mexico-carretera-01092014-medium, 6744.0), (channel partners-mexico-carretera-01102013-medium, 4404.0), (channel partners-mexico-montana-01012014-medium, 28080.0), (channel partners-mexico-montana-01052014-high, 31932.0), (channel partners-mexico-montana-01062014-high, 7248.0), (channel partners-mexico-montana-01112014-low, 8280.0), (channel partners-mexico-paseo-01072014-high, 6852.0), (channel partners-mexico-paseo-01102013-medium, 4404.0), (channel partners-mexico-paseo-01112013-medium, 33156.0), (channel partners-mexico-paseo-01122014-low, 13008.0), (channel partners-mexico-velo-01032014-high, 6000.0), (channel partners-mexico-velo-01062014-high, 7248.0), (channel partners-mexico-velo-01102014-high, 4920.0), (channel partners-mexico-velo-01122014-low, 13008.0), (channel partners-mexico-vtt-01042014-low, 22992.0), (channel partners-mexico-vtt-01092013-high, 12060.0), (channel partners-united states of america-amarilla-01042014-none, 23436.0), (channel partners-united states of america-amarilla-01082014-none, 25692.0), (channel partners-united states of america-amarilla-01092013-low, 23868.0), (channel partners-united states of america-amarilla-01102014-high, 34968.0), (channel partners-united states of america-amarilla-01122013-high, 24180.0), (channel partners-united states of america-carretera-01022014-low, 22296.0), (channel partners-united states of america-carretera-01092014-low, 23364.0), (channel partners-united states of america-carretera-01102013-high, 4632.0), (channel partners-united states of america-montana-01062014-low, 13704.0), (channel partners-united states of america-montana-01112014-medium, 32676.0), (channel partners-united states of america-paseo-01062014-low, 13704.0), (channel partners-united states of america-paseo-01072014-low, 16434.0), (channel partners-united states of america-paseo-01102013-high, 4632.0), (channel partners-united states of america-paseo-01102014-high, 34968.0), (channel partners-united states of america-paseo-01112013-none, 10944.0), (channel partners-united states of america-paseo-01122014-high, 10968.0), (channel partners-united states of america-velo-01032014-low, 17580.0), (channel partners-united states of america-velo-01122014-high, 10968.0), (channel partners-united states of america-vtt-01012014-medium, 23472.0), (channel partners-united states of america-vtt-01052014-high, 21672.0), ...]

[688 rows x 0 columns]

In [71]:
# dup_df = df.groupby('id').agg({'Gross Sales':'max'})
# dupdup_df = dup_df.reset_index().set_index(['id', 'Gross Sales'])
hasil = df.join(dupdup_df,on=['id', 'gross_sales'],how='inner')
hasil

,id,segment,country,product,discount_band,units_sold,manufacturing_price,sale_price,gross_sales,discounts,sales,cogs,profit,date,month_number,month_name,year
0,government-canada-carretera-01012014-none,Government,Canada,Carretera,None,1618.5,3.0,20.0,32370.0,0.00,32370.00,16185.0,16185.00,2014-01-01,1,January,2014
1,government-germany-carretera-01012014-none,Government,Germany,Carretera,None,1321.0,3.0,20.0,26420.0,0.00,26420.00,13210.0,13210.00,2014-01-01,1,January,2014
2,midmarket-france-carretera-01062014-none,Midmarket,France,Carretera,None,2178.0,3.0,15.0,32670.0,0.00,32670.00,21780.0,10890.00,2014-01-06,6,June,2014
3,midmarket-germany-carretera-01062014-none,Midmarket,Germany,Carretera,None,888.0,3.0,15.0,13320.0,0.00,13320.00,8880.0,4440.00,2014-01-06,6,June,2014
4,midmarket-mexico-carretera-01062014-none,Midmarket,Mexico,Carretera,None,2470.0,3.0,15.0,37050.0,0.00,37050.00,24700.0,12350.00,2014-01-06,6,June,2014
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
695,small business-france-amarilla-01032014-high,Small Business,France,Amarilla,High,2475.0,260.0,300.0,742500.0,111375.00,631125.00,618750.0,12375.00,2014-01-03,3,March,2014
696,small business-mexico-amarilla-01102014-high,Small Business,Mexico,Amarilla,High,546.0,260.0,300.0,163800.0,24570.00,139230.00,136500.0,2730.00,2014-01-10,10,October,2014
697,government-mexico-montana-01022014-high,Government,Mexico,Montana,High,1368.0,5.0,7.0,9576.0,1436.40,8139.60,6840.0,1299.60,2014-01-02,2,February,2014
698,government-canada-paseo-01042014-high,Government,Canada,Paseo,High,723.0,10.0,7.0,5061.0,759.15,4301.85,3615.0,686.85,2014-01-04,4,April,2014
699,channel partners-united states of america-vtt-...,Channel Partners,United States of America,VTT,High,1806.0,250.0,12.0,21672.0,3250.80,18421.20,5418.0,13003.20,2014-01-05,5,May,2014

In [72]:
hasil.to_csv("data_cleaned_gx.csv", index=False)